spring:
  application:
    name: spring-kafka-producer

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      client-id: ${spring.application.name}
      properties:
        schema.registry.url: http://localhost:8081
    template:
      observation-enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  endpoints:
    web:
      exposure:
        # Open up all Spring Boot Actuator endpoints for the demo, don't do this in production!
        include: "*"

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}
      env: local

  otlp:
    tracing:
      endpoint: "http://localhost:4317"
      transport: grpc
  opentelemetry:
    resource-attributes:
      some-attribute: some value

kafka:
  producer:
    json:
      enabled: true
      rate: 1000
    avro:
      enabled: true
      rate: 1000